Corrected readme.md and optimised images through ImgBot.
bd808/tools-hatjitsu pull request #3
Opened 2020-03-08 17:36 UTC by Rohan-cod

2020-08-14 01:01 UTC, bd808 commented
@Rohan-cod I did not notice that you had an open pull request here before I did some major changes in this fork of the upstream project. The "toolforge" branch is now our deployed branch. I have reset the "master" branch back to being a clean copy of the upstream's master. Your pull request will need manual rebasing to be reviewable.

I have doubts about the commit in your patch chain that bumps express from 2.5.10 to 4.17.1 with no code changes other than the library version. I find it fairly unlikely that in 2 major version bumps there were no API changes in the express components used in this project. I'm also not sure that it is a great idea for us to make large changes like that in our fork. Contributing changes like that to the upstream project seems like a better idea. We should then be able to bring the upstream changes down into this repo and rebase our local Toolforge specific changes on top of them.

2020-08-19 14:39 UTC, Rohan-cod commented
So Sir, should i remove the commit for the dependency changes and keep the rest of the commits?

2020-08-19 15:48 UTC, bd808 requested changes
> So Sir, should i remove the commit for the dependency changes and keep the rest of the commits?

The library version bump almost certainly needs to be removed. The use of a merge commit to catch up with the new HEAD seems to have done some unhelpful things to your pull request as well.

It really might be easier for you to back up and redo the imagebot and readme changes manually than trying to fix the git history here. But I also wonder if there is any real value in either set of changes? The README changes from the first patch are visual linting more than anything else. The image compression changes seem to be the thing that would be most valuable.

2020-08-19 15:48 UTC, bd808 commented on README.md
> +=======
This file looks like you had merge conflicts and resolved them by keeping both sets of changes? There is certainly a lot of duplicated information in the README now.

2020-08-19 15:48 UTC, bd808 commented on app/css/app.css
> +    background-image: url(../img/title.png);
This is reverting changes that I made recently.

2020-08-19 15:48 UTC, bd808 commented on app/index.ejs
> +        <a href="/hatjitsu/" title="Back to the Lobby">
Another revert of recent changes.

2020-08-19 15:48 UTC, bd808 commented on package.json
> +    "express": "4.17.1",
This is a major API change for express. Bumping the package version here without other code changes will break the entire application. This kind of major change should be made upstream and not in this fork.

2020-08-20 08:04 UTC, Rohan-cod commented
@bd808, I have made the necessary changes. Please have a look.

2020-08-20 22:42 UTC, bd808 commented
> @bd808, I have made the necessary changes. Please have a look.

The state of the collective pull request is still quite messy. If you look at the "Files changed" view you can see that 19 files are changed. Of those 19 files, I believe only the 8 files under  app/img are constructive edits. These are the changes from 3901c57 which were authored by @ImgBotApp.

I would accept a pull request (this one or a fresh start) that includes _only_ this commit. To salvage this pull request, I believe this should work:
```shell
$ cd location_of_your_clone

# Make sure we are on the "master" branch
$ git checkout master

# Fetch the current state of this upstream repo into your working copy's index
$ git add remote upstream https://github.com/toolforge/tool-hatjitsu
$ git fetch upstream

# Replace the contents of the current branch in your working copy
# with contents of the "toolforge" branch from this repo
$ git reset --hard upstream/toolforge

# Copy the 3901c57 commit that will still be in your working copy's index
# to the HEAD of your branch
$ git cherry-pick 3901c57a8dab15fdfc6f89ecea7644120e728c43

# Publish these changes to the "master" branch of your GitHub fork
# which will by extension also update this pull request.
$ git push --force
```

Once those steps are done, this pull request should _only_ show one commit (3901c57, although I am fairly certain it will have a new hash) and 8 files changed (the images in app/img).

2020-08-21 08:49 UTC, Rohan-cod commented
Thanks for the detailed explanation @bd808 😄

2020-08-21 15:52 UTC, merged

2020-08-21 15:53 UTC, bd808 commented
Thanks @Rohan-cod!

2020-08-21 15:57 UTC, Rohan-cod commented
My pleasure 😄.
Thanks for all the support @bd808.